version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.1.0-20211123
    shm_size: 2gb
    environment:
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
      - SCREEN_WIDTH=1360
      - SCREEN_HEIGHT=1020
      - SCREEN_DEPTH=24
      - SCREEN_DPI=96
      - SE_NODE_MAX_SESSIONS=4
    network_mode: "host"
    volumes:
    - ./tests/data:/test_data