name: Pull Request

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.56.1 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        if: always()
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

  unit_tests:
    name: Unit Tests on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.56.1 # MSRV
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Run Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib
      - name: Run Doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.56.1 # MSRV

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'
      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'
      - name: install yew-styles css
        run: npm install yew-styles --prefix tmp
      - name: Build app
        run: trunk -v build --release
      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: ./docker-compose.yml
      - name: Run Integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test interaction -- --test-threads=1

  site:
    name: Deploy site
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.56.1
        override: true
        profile: minimal
        target: wasm32-unknown-unknown
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          cargo-${{ runner.os }}-
    - uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        version: 'latest'
    - name: install yew-styles css
      run: npm install yew-styles --prefix tmp
    - name: Build app
      run: trunk -v build --release
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './dist'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: ${{ github.event.head_commit.message }}
        production-deploy: true
        production-branch: main
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 5
